jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        run: echo "Using secret safely"
        env:
          MY_SECRET: ${{ secrets.SECRET }}
        
